FROM python:3.10

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV MLFLOW_TRACKING_URI=http://mlflow:5000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]